spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://uyhvvswmpwdbsjhx:rkPNVZeIJ5Vn021g4TcW@bcqpw7wghbjre6ofmy6w-mysql.services.clever-cloud.com:3306/bcqpw7wghbjre6ofmy6w
spring.datasource.username=uyhvvswmpwdbsjhx
spring.datasource.password=rkPNVZeIJ5Vn021g4TcW
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#security
jwt.secret = secret
jwt.expiration = 36000